# Generated by Django 3.2.4 on 2021-08-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('area', models.CharField(max_length=20, verbose_name='Área')),
                ('cargo', models.CharField(max_length=20, verbose_name='Cargo')),
                ('adicional', models.TextField(max_length=20, verbose_name='Información Adicional')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['created'],
            },
        ),
    ]
